use fmt_code::{FormattedCode, Lang};
pub mod keywords;
mod cpp;
mod rust;
use self::cpp::convert as convert_cpp;
use self::rust::convert as convert_rust;

pub const AUTOGEN_HEADER: &'static str = concat!("!!! Autogenerated with codespawn (", env!("CARGO_PKG_VERSION"), ") - do not modify. !!!\n");
pub const AUTOGEN_FOOTER: &'static str = "!!! End of autogenerated data. !!!\n";

pub fn code_to_str(fmt_code: &FormattedCode) -> String {
    match fmt_code.language {
        Lang::Cpp  => convert_cpp(&fmt_code.elements, fmt_code.num_tabs, fmt_code.tab_char),
        Lang::Rust => convert_rust(&fmt_code.elements, fmt_code.num_tabs, fmt_code.tab_char),
    }
}
